[package]
name = "pablock"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "A local encrypted dotenv vault"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
pablock-core = { path = "../crates/pablock-core" }
tauri = { version = "2", features = [] }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rpassword = "7"
zeroize = "1"

[dev-dependencies]
tempfile = "3"
assert_cmd = "2"
predicates = "3"
