import { useState } from 'react';
import { api, type Diff, type Preview, type Profile } from '../api';
import { DiffView, ErrorNotice, Modal } from './common';
export function ImportDialog({project,paths,onClose,onDone}:{project:string;paths:string[];onClose:()=>void;onDone:()=>Promise<void>}) {
  const [files,setFiles]=useState(paths.join('\n'));const [replace,setReplace]=useState(false);const [preview,setPreview]=useState<Preview[]|null>(null);const [error,setError]=useState<unknown>();const [busy,setBusy]=useState(false);
  const args=()=>({project,files:files.split('\n').map(p=>p.trim()).filter(Boolean),replace});
  return <Modal title="Import dotenv files" onClose={onClose}><p>Enter one path per line, relative to the project root. Template values are discarded.</p><label>Files<textarea value={files} rows={4} placeholder={'.env\napps/api/.env.production'} onChange={e=>{setFiles(e.target.value);setPreview(null);}}/></label><fieldset className="mode-switch"><legend>Import mode</legend><label><input type="radio" name="mode" checked={!replace} onChange={()=>{setReplace(false);setPreview(null);}}/>Merge <span>Keep vault keys absent from the file</span></label><label><input type="radio" name="mode" checked={replace} onChange={()=>{setReplace(true);setPreview(null);}}/>Replace <span>Record absent keys as deleted</span></label></fieldset><ErrorNotice error={error}/>{preview&&<div className="transfer-preview">{preview.map(p=><section key={p.path}><h3>{p.path}<span className="badge">{p.kind}</span></h3><DiffView diff={p.diff}/>{p.warnings.map(w=><p className="warning" key={w}>{w}</p>)}</section>)}</div>}<div className="modal-actions"><button onClick={onClose}>Cancel</button>{preview?<button className="primary" disabled={busy} onClick={async()=>{setBusy(true);setError(undefined);try{await api('import',args());await onDone();onClose();}catch(e){setError(e);setPreview(null);}finally{setBusy(false);}}}>Confirm import</button>:<button className="primary" disabled={busy||!files.trim()} onClick={async()=>{setBusy(true);setError(undefined);try{setPreview(await api('preview_import',args()));}catch(e){setError(e);}finally{setBusy(false);}}}>{busy?'Reading files…':'Preview import'}</button>}</div></Modal>;
}
export function ExportDialog({profile,onClose}:{profile:Profile;onClose:()=>void}) {
 const [target,setTarget]=useState(profile.path);const [diff,setDiff]=useState<Diff|null>(null);const [overwrite,setOverwrite]=useState(false);const [error,setError]=useState<unknown>();const [busy,setBusy]=useState(false);const [done,setDone]=useState(false);
 return <Modal title="Diff & export" onClose={onClose}><p>Compare the destination with the vault. Added and changed keys will be written from the vault; removed keys will disappear from the file.</p><label>Destination file<input value={target} disabled={done} onChange={e=>{setTarget(e.target.value);setDiff(null);setOverwrite(false);}}/></label><p className="help">Destination must be a regular file inside the project. Symlinks are rejected. Export sorts keys and replaces formatting and comments.</p><ErrorNotice error={error}/>{diff&&<><DiffView diff={diff}/><div className="export-warning">Export writes directly to the file and preserves existing permissions. An interrupted write may leave a partial file.</div><label className="checkbox"><input type="checkbox" checked={overwrite} disabled={done} onChange={e=>setOverwrite(e.target.checked)}/>Allow replacing the destination if it already exists</label></>}{done&&<div className="notice" role="status">Export complete.</div>}<div className="modal-actions"><button onClick={onClose}>{done?'Close':'Cancel'}</button>{!done&&(diff?<button className="primary" disabled={busy} onClick={async()=>{setBusy(true);setError(undefined);try{await api('export',{profile:profile.id,target,overwrite});setDone(true);}catch(e){setError(e);}finally{setBusy(false);}}}>Export file</button>:<button className="primary" disabled={busy||!target} onClick={async()=>{setBusy(true);setError(undefined);try{setDiff(await api('diff',{profile:profile.id,target}));}catch(e){setError(e);}finally{setBusy(false);}}}>Compare with disk</button>)}</div></Modal>;
}
