import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, Route, Routes, useNavigate } from 'react-router-dom';
import { FolderPlus, Folder, LockKeyhole, ShieldCheck, KeyRound, ArrowRight, Terminal, ChevronRight } from 'lucide-react';
import { api } from './api';
import { Brand, ErrorNotice, Modal } from './components/common';
import ProjectPage from './components/ProjectPage';
export default function App() {
  const query=useQuery({queryKey:['status'],queryFn:()=>api('status',{})});
  const client=useQueryClient();const navigate=useNavigate();const [settings,setSettings]=useState(false);const [error,setError]=useState<unknown>();
  if(query.isPending) return <div className="loading">Opening Pablock…</div>;
  if(query.isError) return <main className="auth"><Brand/><ErrorNotice error={query.error}/><button onClick={()=>void query.refetch()}>Retry connection</button></main>;
  if(!query.data.unlocked) return <Auth initialized={query.data.initialized} onOpen={async()=>{client.clear();navigate('/');await client.invalidateQueries();}}/>;
  async function lock() {try {await api('lock',{});setSettings(false);client.clear();navigate('/');await client.invalidateQueries();}catch(e){setError(e);}}
  return <div className="app"><aside className="sidebar"><Link to="/" className="brand-link"><Brand/></Link><div className="workspace-label">LOCAL WORKSPACE</div><Link className="nav-link" to="/"><Folder size={18}/> Projects <ChevronRight size={14}/></Link><div className="sidebar-note"><ShieldCheck size={20}/><p>On your machine.<br/>Under your control.</p><span>Encrypted with Stronghold</span></div><div className="sidebar-bottom"><div className="vault-state"><span className="status-dot"/> Vault unlocked</div><button onClick={()=>setSettings(true)}><KeyRound size={16}/>Change password</button><button onClick={()=>void lock()}><LockKeyhole size={16}/>Lock vault</button></div></aside><div className="workspace"><header className="topbar"><span>YOUR ENVIRONMENT, SECURED</span><span className="local-badge"><span className="status-dot"/>Local only</span></header><ErrorNotice error={error}/><Routes><Route path="/" element={<Projects/>}/><Route path="/project/:projectId" element={<ProjectPage/>}/><Route path="*" element={<Projects/>}/></Routes><footer><LockKeyhole size={12}/> Secrets stay in your local vault <span>PABLOCK 1.0</span></footer></div>{settings&&<PasswordDialog onClose={()=>setSettings(false)}/>}</div>;
}
function Auth({initialized,onOpen}:{initialized:boolean;onOpen:()=>Promise<void>}) {
  const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>();
  return <main className="auth"><Brand/><div className="auth-panel"><span className="eyebrow">YOUR LOCAL ENV VAULT</span><h1>{initialized?'Welcome back.':'A safer home for your secrets.'}</h1><p>{initialized?'Unlock your projects with your master password.':'Create a master password to encrypt your dotenv values on this machine.'}</p><form onSubmit={async e=>{e.preventDefault();if(!initialized&&password!==confirm){setError('Passwords do not match');return;}setBusy(true);const secret=password;setPassword('');setConfirm('');try{await api(initialized?'unlock':'init',{password:secret});await onOpen();}catch(e){setError(e);}finally{setBusy(false);}}}><label>Master password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={initialized?'current-password':'new-password'} required autoFocus/></label>{!initialized&&<><label>Confirm password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password" required/></label><p className="help">There is no password recovery. Keep your master password somewhere safe.</p></>}<ErrorNotice error={error}/><button className="primary full" disabled={busy}>{busy?'Opening vault…':initialized?'Unlock vault':'Create vault'}<ArrowRight size={17}/></button></form></div><p className="auth-foot"><ShieldCheck size={16}/>Local storage. No account. No cloud.</p></main>;
}
function Projects() {
  const q=useQuery({queryKey:['projects'],queryFn:()=>api('projects',{})});const [add,setAdd]=useState(false);const navigate=useNavigate();const client=useQueryClient();
  return <main><div className="page-heading"><div><div className="eyebrow">WORKSPACE</div><h1>Your projects<span className="count">{q.data?.length??0}</span></h1><p>Keep your environments organized and your values encrypted.</p></div><button className="primary" onClick={()=>setAdd(true)}><FolderPlus size={17}/>Add project</button></div><ErrorNotice error={q.error}/>{q.isPending?<p>Loading projects…</p>:q.data?.length?<div className="project-grid">{q.data.map(p=><Link className="project-card" to={`/project/${p.id}`} key={p.id}><div className="project-card-top"><span className="folder-tile"><Folder size={24}/></span><ChevronRight size={18}/></div><h2>{p.name}</h2><code>{p.root}</code><div className="card-bottom"><span className="status-dot"/>Local project<span>Open project <ArrowRight size={14}/></span></div></Link>)}</div>:<div className="empty"><FolderPlus size={36}/><h2>Add your first project</h2><p>Choose a project directory, then scan for dotenv files.</p><button onClick={()=>setAdd(true)}>Add project</button></div>}<div className="cli-tip"><Terminal size={21}/><div><strong>Same vault. Your terminal.</strong><p>Access your projects with <code>pablock secret list</code>. Lock the GUI vault first to use the CLI.</p></div></div>{add&&<AddProject onClose={()=>setAdd(false)} onAdded={async id=>{await client.invalidateQueries({queryKey:['projects']});navigate(`/project/${id}`);}}/>}</main>;
}
function AddProject({onClose,onAdded}:{onClose:()=>void;onAdded:(id:string)=>Promise<void>}) {
 const [path,setPath]=useState('');const [name,setName]=useState('');const [error,setError]=useState<unknown>();const [busy,setBusy]=useState(false);
 return <Modal title="Add project" onClose={onClose}><p>Enter the absolute path to your project directory.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const p=await api('add_project',{path,name:name||undefined});await onAdded(p.id);onClose();}catch(e){setError(e);}finally{setBusy(false);}}}><label>Project directory<input autoFocus placeholder="/home/you/projects/my-app" value={path} onChange={e=>setPath(e.target.value)} required/></label><label>Display name <span className="muted">optional</span><input value={name} onChange={e=>setName(e.target.value)} maxLength={256}/></label><p className="help">Pablock adds a .pablock.toml marker containing only the project ID.</p><ErrorNotice error={error}/><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>Add project</button></div></form></Modal>;
}
function PasswordDialog({onClose}:{onClose:()=>void}) {
 const [current,setCurrent]=useState('');const [next,setNext]=useState('');const [confirm,setConfirm]=useState('');const [error,setError]=useState<unknown>();const [busy,setBusy]=useState(false);
 return <Modal title="Change master password" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();if(next!==confirm){setError('Passwords do not match');return;}setBusy(true);const args={current,new:next};setCurrent('');setNext('');setConfirm('');try{await api('password',args);onClose();}catch(e){setError(e);}finally{setBusy(false);}}}><label>Current password<input type="password" autoComplete="current-password" required value={current} onChange={e=>setCurrent(e.target.value)}/></label><label>New password<input type="password" autoComplete="new-password" required value={next} onChange={e=>setNext(e.target.value)}/></label><label>Confirm new password<input type="password" autoComplete="new-password" required value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><p className="help">Your vault will be encrypted with the new password. There is no password recovery.</p><ErrorNotice error={error}/><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>Change password</button></div></form></Modal>;
}
